dubbo:
  application:
    name: a901
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20881
  scan:
    base-packages: cn.com.sinosoft.a901
  consumer:
    check: false